### ISSUE TITLE
Its possible to use nvidia docker with ECS without having to copy drivers manually 

### ISSUE THREAD

**Issue by ghost** [bfolkens/nvidia-docker-bootstrap#2]
See my comments on this issue.
You can usw the AMI that I created or just follow same steps.

https://github.com/aws/amazon-ecs-agent/issues/656

**Comment by bfolkens** [comment]
That's great news.  What did you do to build the image?  In other words, what makes it work?

**Comment by ghost** [comment]
You can read the detailed process here, https://github.com/aws/amazon-ecs-agent/issues/656

Essentially use the AWS Deep Learning AMI and install NVidia docker, ECS-agent, additionally when you specify GPU container tasks make sure to run them in privileged mode and mount the host directory containing the Drivers ("/var/lib/nvidia-docker/volumes/nvidia_driver/latest") as a volume. AWS already had instructions to user Deep Learning AMI with ECS agent for AWS Batch. 
I just made couple of changes to update the script.

**Comment by chenliu0831** [comment]
Hey is it possible to not using privileged mode? Thanks

**Comment by ejmarten** [comment]
I would think that you would have to use privileged mode in order to get
direct access to the gpu.  That seems like a docker thing, not a driver
thing.

Erik

**Comment by ghost** [comment]
@chenliu0831 With new nvidia-docker 2.0 it might be possible since the newer version replaces the default docker runtime with nvidia-docker runtime.
